config/routes.rb
SampleApp::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]

  root "static_pages#home"

  get '/help',    to: 'static_pages#help'
  get '/about',   to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/signup',  to: 'users#new'
  get '/signin',  to: 'sessions#new'
  delete '/signout',  to: 'sessions#destroy'

  

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string(255)
#  email           :string(255)
#  created_at      :datetime
#  updated_at      :datetime
#  password_digest :string(255)
#  remember_token  :string(255)
#  admin           :boolean          default(FALSE)
#

require 'bcrypt'



class User < ActiveRecord::Base

  has_secure_password
  has_many :microposts, dependent: :destroy

  before_save { email.downcase! }
  before_save :create_remember_token

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX, message: "Not allowed email" }, uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 6 }#, confirmation: true
  validates :password_confirmation, presence: true

  def feed
    # Это предварительное решение. См. полную реализацию в "Following users".
    Micropost.where("user_id = ?", id)
  end

  private

  def create_remember_token
    self.remember_token = SecureRandom.urlsafe_base64
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include SessionsHelper

  # Force signout to prevent CSRF attacks
  def handle_unverified_request
    sign_out
    super
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
    if signed_in?
      @micropost  = current_user.microposts.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end

  def help
  end

  def about

  end
  def action

  end
  def contact

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signed_in_user, only: [:index, :edit, :update, :destroy]
  before_filter :correct_user,   only: [:edit, :update]
  before_filter :admin_user,     only: :destroy
  before_filter :redirect_home,  only: [:new, :create]

  def index
    @users = User.paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.paginate(page: params[:page])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end
  def edit
    @user = User.find(params[:id])
  end
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      sign_in @user
      redirect_to @user
    else
      render 'edit'
    end

  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User destroyed."
    redirect_to users_url
  end

  private

  def user_params
    params.require(:user).permit(:email, :name, :password, :password_confirmation)
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_path) unless current_user?(@user)
  end

  def admin_user
    redirect_to(root_path) unless current_user.admin?
  end

  def redirect_home
    redirect_to(root_path) if current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_title(page_title)
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end

end

app/helpers/microposts_helper.rb
module MicropostsHelper

  def wrap(content)
    sanitize(raw(content.split.map{ |s| wrap_long_string(s) }.join(' ')))
  end

  private

  def wrap_long_string(text, max_width = 30)
    zero_width_space = "&#8203;"
    regex = /.{1,#{max_width}}/
    (text.length < max_width) ? text :
        text.scan(regex).join(zero_width_space)
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end

end

app/views/layouts/_footer.html.haml
%footer.footer.container
  %small
    %a{href: "http://railstutorial.org/"}
      Rails Tutorial
    by Michael Hartl
  %nav
    %ul
      %li= link_to "About", about_path
      %li= link_to "Contact", contact_path
      %li
        %a{href: "http://news.railstutorial.org/"}
          News
  = debug(params) if Rails.env.development?

app/views/layouts/_header.html.haml
%header.navbar.navbar-fixed-top.navbar-inverse
  %div.navbar-inner
    %div.container
      = link_to "sample app", root_path, id: "logo"
      %nav
        %ul.nav.pull-right
          %li= link_to "Home", root_path
          %li= link_to "Help", help_path
          - if signed_in?
            %li= link_to "Users", users_path
            %li#fat-menu.dropdown
              %a{ href: "#", class: "dropdown-toggle", :data =>{toggle: 'dropdown'}}
                Account
                %b.caret
              %ul.dropdown-menu
                %li= link_to "Profile", current_user
                %li= link_to "Settings", edit_user_path(current_user)
                %li.divider
                %li= link_to "Sign out", signout_path, method: "delete"
          - else
            %li= link_to "Sign in", signin_path

app/views/layouts/_shim.html.haml
/[if lt IE 9]
  %script{ src: "http://html5shim.googlecode.com/svn/trunk/html5.js", type: "text/javascript"}

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title
      = full_title(yield(:title))
    = stylesheet_link_tag    "application", media: "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    = render 'layouts/shim'
  %body
    = render 'layouts/header'
    %div.container
      - flash.each do |key, value|
        = content_tag(:div, value, class: "alert alert-#{key}")
      = yield
    = render 'layouts/footer'

app/views/microposts/_micropost.html.haml
%li
  %span.content
    = micropost.content
  %span.timestamp
    = "Posted #{time_ago_in_words(micropost.created_at)} ago."
  = render 'shared/delete_link', object: micropost

app/views/shared/_delete_link.html.haml
- if current_user?(object.user)
  = link_to "delete", object, method: :delete, data: { confirm: "You sure?" }, title: object.content

app/views/shared/_error_messages.html.haml
- if object.errors.any?
  %div#error_explanation
    %div.alert.alert-error
      = "The form contains #{pluralize(object.errors.count, 'error')}."
    %ul
      - object.errors.full_messages.each do |msg|
        %li= "* #{msg}"

app/views/shared/_feed.html.haml
-if @feed_items.any?
  %ol.microposts
    = render partial: 'shared/feed_item', collection: @feed_items
  = will_paginate @feed_items

app/views/shared/_feed_item.html.haml
%li{id:"#{feed_item.id}"}
  = link_to gravatar_for(feed_item.user), feed_item.user
  %span.user
    = link_to feed_item.user.name, feed_item.user
  %span.content
    = wrap feed_item.content
  %span.timestamp
    = "Posted #{time_ago_in_words(feed_item.created_at)} ago."
  = render 'shared/delete_link', object: feed_item

app/views/shared/_home_signedin_user.html.haml
%div.row
  %aside.span4
    %section
      = render 'shared/user_info'
    %section
      = render 'shared/micropost_form'
  %div.span8
    %h3
      Micropost Feed
    = render 'shared/feed'

app/views/shared/_home_welcome.html.haml
%div.center.hero-unit
  %h1 Welcome to the Sample App
  %h2
    This is the home page for the
    %a{ href: "http://railstutorial.org/"}
      Ruby on Rails Tutorial
    sample application.
  = link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary"
= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/'

app/views/shared/_micropost_form.html.haml
= form_for(@micropost) do |f|
  = render 'shared/error_messages', object: f.object
  %div.field
    = f.text_area :content, placeholder: "Compose new micropost...", onKeyDown:"textCounter('micropost_content','counter',140);", onKeyUp: "textCounter('micropost_content','counter',140);"
    %input{ id:"counter", readonly: "true", type:"text", size:"30"}
  = f.submit "Post", class: "btn btn-large btn-primary"
:javascript
  textCounter('micropost_content','counter',140);

app/views/shared/_user_info.html.haml
%a{ href: "#{ user_path(current_user)}"}
  = gravatar_for current_user, size: 52
%h1= current_user.name
%span= link_to "view my profile", current_user
%span= pluralize(current_user.microposts.count, "micropost")

app/views/static_pages/about.html.erb
<%= provide(:title, "About Us") %>
<h1>About Us</h1>
<p>
  The <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
  is a project to make a book and screencasts to teach web development
  with <a href="http://rubyonrails.org/">Ruby on Rails</a>. This
  is the sample application for the tutorial.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact Ruby on Rails Tutorial about the sample app at the
  <a href="http://railstutorial.org/contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<%= provide(:title, "Help") %>
<h1>Help</h1>
<p>
  Get help on the Ruby on Rails Tutorial at the
  <a href="http://railstutorial.org/help">Rails Tutorial help page</a>.
  To get help on this sample app, see the
  <a href="http://railstutorial.org/book">Rails Tutorial book</a>.
</p>

app/views/static_pages/home.html.haml
- if signed_in?
  = render 'shared/home_signedin_user'
- else
  = render 'shared/home_welcome'

app/views/users/_fields.html.haml
= render 'shared/error_messages', object: f.object
= f.label :name
= f.text_field :name
= f.label :email
= f.text_field :email
= f.label :password
= f.password_field :password
= f.label :password_confirmation, "Confirmation"
= f.password_field :password_confirmation

app/views/users/_user.html.haml
%li
  = gravatar_for user, size: 52
  = link_to user.name, user
  -if current_user.admin? && !current_user?(user)
    |
    = link_to "delete", user, method: :delete, data: { confirm: "You sure?" }

app/views/users/edit.html.haml
-content_for(:title, "Edit user")
%h1 Update your profile
%div.row
  %div.span6.offset3
    = form_for @user do |f|
      = render 'fields', f: f
      = f.submit "Save changes", class: "btn btn-large btn-primary"
    = gravatar_for @user
    %a{ href: "http://gravatar.com/emails", target: "_blank"}
      change

app/views/users/index.html.haml
-content_for(:title, "All users")
%h1 All users
=will_paginate
%ul.users
  = render @users
=will_paginate

app/views/users/new.html.haml
-content_for(:title, "Sign up")
%h1 Sign up
%div.row
  %div.span6.offset3
    = form_for @user do |f|
      = render 'fields', f: f
      = f.submit "Create my account", class: "btn btn-large btn-primary"

app/views/users/show.html.haml
- content_for(:title,  @user.name)
%div#row
  %aside#span4
    %section
      %h1
        = gravatar_for @user, size: 100
        = "#{@user.name}, #{@user.email}"
    %div.span8
      - if @user.microposts.any?
        %h3 Microposts
        =will_paginate @microposts
        = @user.microposts.count
        %ol.microposts
          = render @microposts
        =will_paginate @microposts